name: stock_quant
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - torchvision
  - cpuonly
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - joblib
  - xgboost
  - lightgbm
  - catboost
  - django
  - django-cors-headers
  - requests
  - lxml
  - beautifulsoup4
  - matplotlib
  - shap
  - statsmodels
  - pyarrow
  - python-dotenv
  - pip
  - pip:
    - tushare
    - akshare
    - torch-geometric
    - transformers
    - sentencepiece
    - ftfy
    - baostock
